[section .metadata]
.file: index.mjs
[section .constants]
.0: "Error"
.1: "length"
.2: "test"
[section .data]
0: NEO_ASM_PUSH_SCOPE
2: NEO_ASM_LOAD "Error"
12: NEO_ASM_PUSH_ARRAY 0
22: NEO_ASM_PUSH_VALUE 1
28: NEO_ASM_PUSH_STRING "length"
38: NEO_ASM_GET_FIELD
40: NEO_ASM_PUSH_STRING "test"
50: NEO_ASM_SET_FIELD
52: NEO_ASM_PUSH_CALL_STACK 1,7
62: NEO_ASM_NEW
64: NEO_ASM_POP_CALL_STACK
66: NEO_ASM_THROW
68: NEO_ASM_HLT
70: NEO_ASM_POP_SCOPE
